<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net5.0;net6.0;net7.0;net8.0;net9.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Product>Dirk Tamke's SortCollection</Product>
    <PackageId>SinusSoftware.SortCollection</PackageId>
    <Version>1.5</Version>
    <PackageReleaseNotes>This is release 1.5 with following changes:

* Add Targetframework .Net10.0
* Add descending function for Countingsort
* Add descending function for Radixsort
* Add property signature (Func&lt;TSource, TKey&gt;) for Introsort
* Add property signature (Func&lt;TSource, TKey&gt;) for Timsort
* Add Quicksort
* Add parallel Quicksort (Multi-Threading)
* Add parallel Mergesort (Multi-Threading, Asynchron)</PackageReleaseNotes>
    <PackageProjectUrl>https://github.com/SinusSoftware/SortCollection</PackageProjectUrl>
    <Authors>Dirk Tamke</Authors>
    <Company>Dirk Tamke</Company>
    <PackageTags>Sortcollection; Sortalgorithms; Bubblesort; Selectionsort; Insertionsort; Heapsort; Mergesort; Countingsort; Shellsort; Radixsort; SlowSort; IntroSort; Timsort; Shakersort; QuickSort; parallel; Thread; Multithreading; async</PackageTags>
    <Description>This package contains the following sorting algorithms: Bubblesort, Selectionsort, Insertionsort, Heapsort, Mergesort, Countingsort, Shellsort, Radixsort, SlowSort, IntroSort, Timsort, Shakersort, QuickSort, parallel Quicksort and parallel Mergesort. You can use it like standard sort. Example: List.Sort() =&gt; List.SortWithHeapSort()</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/SinusSoftware/SortCollection</RepositoryUrl>
    <Title>SortCollection from SinusSoftware</Title>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <Content Include="ReadMe.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </Content>
  </ItemGroup>
</Project>
